# typed: false
# frozen_string_literal: true

# Autogenerated by uatu's release workflow (scripts/generate-cask.ts).
# Do not edit by hand — the next release overwrites this file.
cask "uatu-desktop@edge" do
  version "0.7.0-edge.20260924082728.c66bcf9"

  on_arm do
    sha256 "6d7360e38647421614e582914e2fcbca0be021d50347f946f6fa9f4ab6b95ddc"
    url "https://github.com/tjakobsson/uatu/releases/download/edge/UatuCode-Desktop-arm64.zip"
  end
  on_intel do
    sha256 "fafec2719bdfab7d1b383be2068579192fb2944f8aeff5bfdd0bbfc2bf2551a3"
    url "https://github.com/tjakobsson/uatu/releases/download/edge/UatuCode-Desktop-x64.zip"
  end

  name "UatuCode Desktop"
  desc "Desktop app for uatu, the docs-tree watcher with Markdown/AsciiDoc preview"
  homepage "https://github.com/tjakobsson/uatu"

  depends_on macos: :tahoe
  conflicts_with cask: "uatu-desktop"

  app "UatuCode Desktop.app"

  zap trash: [
    "~/Library/Preferences/se.coll8.uatucode.desktop.plist",
    "~/Library/WebKit/se.coll8.uatucode.desktop",
  ]
end
