# typed: false
# frozen_string_literal: true

# Autogenerated by uatu's release workflow (scripts/generate-cask.ts).
# Do not edit by hand — the next release overwrites this file.
cask "uatu-desktop@edge" do
  version "0.6.2-edge.20260906075425.b697458"

  on_arm do
    sha256 "e2692e8266f195baa6671bc6e5b8aebbdf3c8b5378f5ce42a8a4a0b5f04ea51d"
    url "https://github.com/tjakobsson/uatu/releases/download/edge/UatuCode-Desktop-arm64.zip"
  end
  on_intel do
    sha256 "b09c66c5dcdc3e22afc128796547bf08f0aad2c6cbf561962d66d0f08eba8163"
    url "https://github.com/tjakobsson/uatu/releases/download/edge/UatuCode-Desktop-x64.zip"
  end

  name "UatuCode Desktop"
  desc "Desktop app for uatu, the docs-tree watcher with Markdown/AsciiDoc preview"
  homepage "https://github.com/tjakobsson/uatu"

  depends_on macos: :tahoe
  conflicts_with cask: "uatu-desktop"

  app "UatuCode Desktop.app"

  zap trash: [
    "~/Library/Preferences/se.coll8.uatucode.desktop.plist",
    "~/Library/WebKit/se.coll8.uatucode.desktop",
  ]
end
