# typed: false
# frozen_string_literal: true

# Autogenerated by uatu's release workflow (scripts/generate-cask.ts).
# Do not edit by hand — the next release overwrites this file.
cask "uatu-desktop" do
  version "0.6.2"

  on_arm do
    sha256 "2e48a7d5538a117c923f18bd3873aa99795efc9207117383b748c14c33213550"
    url "https://github.com/tjakobsson/uatu/releases/download/v0.6.2/UatuCode-Desktop-arm64.zip"
  end
  on_intel do
    sha256 "f981cadee2322915d8dcdd20bf1e6e7212185f188921375f31830ed27e4727d2"
    url "https://github.com/tjakobsson/uatu/releases/download/v0.6.2/UatuCode-Desktop-x64.zip"
  end

  name "UatuCode Desktop"
  desc "Desktop app for uatu, the docs-tree watcher with Markdown/AsciiDoc preview"
  homepage "https://github.com/tjakobsson/uatu"

  depends_on macos: :tahoe
  conflicts_with cask: "uatu-desktop@edge"

  app "UatuCode Desktop.app"

  zap trash: [
    "~/Library/Preferences/se.coll8.uatucode.desktop.plist",
    "~/Library/WebKit/se.coll8.uatucode.desktop",
  ]
end
