# typed: false
# frozen_string_literal: true

# Autogenerated by uatu's release workflow (scripts/generate-cask.ts).
# Do not edit by hand — the next release overwrites this file.
cask "uatu-desktop@edge" do
  version "0.6.1-edge.20260826040309.3e23a75"

  on_arm do
    sha256 "d8769c2f8ec470170c9aa6ffedfac98d6513643f9829270185852b484dc566ba"
    url "https://github.com/tjakobsson/uatu/releases/download/edge/UatuCode-Desktop-arm64.zip"
  end
  on_intel do
    sha256 "b53c5d42541d8d5c48838a1fef77e7d13ef39cab09d0ce4a25ad1e0c1ba0810a"
    url "https://github.com/tjakobsson/uatu/releases/download/edge/UatuCode-Desktop-x64.zip"
  end

  name "UatuCode Desktop"
  desc "Desktop app for uatu, the docs-tree watcher with Markdown/AsciiDoc preview"
  homepage "https://github.com/tjakobsson/uatu"

  depends_on macos: :tahoe
  conflicts_with cask: "uatu-desktop"

  app "UatuCode Desktop.app"

  zap trash: [
    "~/Library/Preferences/se.coll8.uatucode.desktop.plist",
    "~/Library/WebKit/se.coll8.uatucode.desktop",
  ]
end
