# typed: false
# frozen_string_literal: true

# Autogenerated by uatu's release workflow (scripts/generate-cask.ts).
# Do not edit by hand — the next release overwrites this file.
cask "uatu-desktop" do
  version "0.7.0"

  on_arm do
    sha256 "1e254edb4f33eb257d2839a14c74ef70d51484aa26f2f599bd477fd53d5b48cd"
    url "https://github.com/tjakobsson/uatu/releases/download/v0.7.0/UatuCode-Desktop-arm64.zip"
  end
  on_intel do
    sha256 "19c28ba9b04bf8f5e98168650faaa43741c17379f9a5f55ac5c98070a58287d2"
    url "https://github.com/tjakobsson/uatu/releases/download/v0.7.0/UatuCode-Desktop-x64.zip"
  end

  name "UatuCode Desktop"
  desc "Desktop app for uatu, the docs-tree watcher with Markdown/AsciiDoc preview"
  homepage "https://github.com/tjakobsson/uatu"

  depends_on macos: :tahoe
  conflicts_with cask: "uatu-desktop@edge"

  app "UatuCode Desktop.app"

  zap trash: [
    "~/Library/Preferences/se.coll8.uatucode.desktop.plist",
    "~/Library/WebKit/se.coll8.uatucode.desktop",
  ]
end
