# typed: false
# frozen_string_literal: true

# Autogenerated by uatu's release workflow (scripts/generate-cask.ts).
# Do not edit by hand — the next release overwrites this file.
cask "uatu-desktop" do
  version "0.6.1"

  on_arm do
    sha256 "145de4a5a0bb2a03a21ab01b8a4bebc435ea73322ee172e10aa0046d10bd47b2"
    url "https://github.com/tjakobsson/uatu/releases/download/v0.6.1/UatuCode-Desktop-arm64.zip"
  end
  on_intel do
    sha256 "4d41754f25b6c04c82476ceee5e7d1ad6630dfa3b5d6b1fe7e3786f6534cfc21"
    url "https://github.com/tjakobsson/uatu/releases/download/v0.6.1/UatuCode-Desktop-x64.zip"
  end

  name "UatuCode Desktop"
  desc "Desktop app for uatu, the docs-tree watcher with Markdown/AsciiDoc preview"
  homepage "https://github.com/tjakobsson/uatu"

  depends_on macos: :tahoe
  conflicts_with cask: "uatu-desktop@edge"

  app "UatuCode Desktop.app"

  zap trash: [
    "~/Library/Preferences/se.coll8.uatucode.desktop.plist",
    "~/Library/WebKit/se.coll8.uatucode.desktop",
  ]
end
