# typed: false
# frozen_string_literal: true

# Autogenerated by uatu's release workflow (scripts/generate-formula.ts).
# Do not edit by hand — the next release overwrites this file.
class UatuEdge < Formula
  desc "Docs-tree watcher with Markdown/AsciiDoc preview and review-load score"
  homepage "https://github.com/tjakobsson/uatu"
  version "0.4.0-edge.20260810054620.3366693"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/tjakobsson/uatu/releases/download/edge/uatu-darwin-arm64.zip"
      sha256 "4f992ad93269382c54ce5a7262dd05d28afc26ae6c5254c466ad292636eeea26"
    end
    on_intel do
      url "https://github.com/tjakobsson/uatu/releases/download/edge/uatu-darwin-x64.zip"
      sha256 "c6d3b24b52f7d398f6748544c3246866362505d30e42cd438e3f6180884d1afd"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/tjakobsson/uatu/releases/download/edge/uatu-linux-arm64.tar.gz"
      sha256 "7d8a98848f751eb3028468393615c45c42ebd4946b98ec3e9736aa0249800a6a"
    end
    on_intel do
      url "https://github.com/tjakobsson/uatu/releases/download/edge/uatu-linux-x64.tar.gz"
      sha256 "3faa45f7c291e43640efac7abc1311b5208873cd73325804fc7db0372d9e83c9"
    end
  end

  conflicts_with "uatu", because: "both install a `uatu` binary"

  def install
    bin.install "uatu"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/uatu --version")
  end
end
