# typed: false
# frozen_string_literal: true

# Autogenerated by uatu's release workflow (scripts/generate-formula.ts).
# Do not edit by hand — the next release overwrites this file.
class UatuEdge < Formula
  desc "Docs-tree watcher with Markdown/AsciiDoc preview and review-load score"
  homepage "https://github.com/tjakobsson/uatu"
  version "0.7.0-edge.20260921050737.7287ac0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/tjakobsson/uatu/releases/download/edge/uatu-darwin-arm64.zip"
      sha256 "d3ffd093e90e2bb8f5355af03753a7a29e092377ceda02879935dc0e3ff77ab6"
    end
    on_intel do
      url "https://github.com/tjakobsson/uatu/releases/download/edge/uatu-darwin-x64.zip"
      sha256 "dfa107040f5263a60909dc6f4954cf9bf7ba4cf5e6815fed0569b74947044183"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/tjakobsson/uatu/releases/download/edge/uatu-linux-arm64.tar.gz"
      sha256 "6b83eb680cfa343231eac850eab3546aee048fc286fcc59bb10287ea782e3c60"
    end
    on_intel do
      url "https://github.com/tjakobsson/uatu/releases/download/edge/uatu-linux-x64.tar.gz"
      sha256 "a0cfd0ecf22c6c1c30b6924ec783d130f760fdefb9d2556bd1858e84a29615a9"
    end
  end

  conflicts_with "uatu", because: "both install a `uatu` binary"

  def install
    bin.install "uatu"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/uatu --version")
  end
end
