# typed: false
# frozen_string_literal: true

# Autogenerated by uatu's release workflow (scripts/generate-formula.ts).
# Do not edit by hand — the next release overwrites this file.
class Uatu < Formula
  desc "Docs-tree watcher with Markdown/AsciiDoc preview and review-load score"
  homepage "https://github.com/tjakobsson/uatu"
  version "0.5.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/tjakobsson/uatu/releases/download/v0.5.0/uatu-darwin-arm64.zip"
      sha256 "f17755cb1928be98c823afdfb0c67f74fdd84248449ee722159690fdfaf3ebe0"
    end
    on_intel do
      url "https://github.com/tjakobsson/uatu/releases/download/v0.5.0/uatu-darwin-x64.zip"
      sha256 "c35b13a7cbcad433660452a31e1a1fb9813f25611aa9f91b1c9fbbec909217e2"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/tjakobsson/uatu/releases/download/v0.5.0/uatu-linux-arm64.tar.gz"
      sha256 "66583904adad0667ee4a37482a757124e02d3090a320e29a5a1f21245b979f99"
    end
    on_intel do
      url "https://github.com/tjakobsson/uatu/releases/download/v0.5.0/uatu-linux-x64.tar.gz"
      sha256 "11429fa05b33a972c0469f4a348d7b2b4172f1b345ea05057466326022897e37"
    end
  end

  conflicts_with "uatu-edge", because: "both install a `uatu` binary"

  def install
    bin.install "uatu"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/uatu --version")
  end
end
