# typed: false
# frozen_string_literal: true

# Autogenerated by uatu's release workflow (scripts/generate-formula.ts).
# Do not edit by hand — the next release overwrites this file.
class Uatu < Formula
  desc "Docs-tree watcher with Markdown/AsciiDoc preview and review-load score"
  homepage "https://github.com/tjakobsson/uatu"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/tjakobsson/uatu/releases/download/v0.3.0/uatu-darwin-arm64.zip"
      sha256 "37d228a04499a2661dd789424d13d20386becf567ee63c64b26743bad45b48b7"
    end
    on_intel do
      url "https://github.com/tjakobsson/uatu/releases/download/v0.3.0/uatu-darwin-x64.zip"
      sha256 "d611b7d2c5542fe7ecbdf40a76759258c9f197d72b45597d67eedf2af9b7c687"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/tjakobsson/uatu/releases/download/v0.3.0/uatu-linux-arm64.tar.gz"
      sha256 "56cf225f14cc9efaec21fbb586acd4bafcf675bbdc49bb121608bce755abd761"
    end
    on_intel do
      url "https://github.com/tjakobsson/uatu/releases/download/v0.3.0/uatu-linux-x64.tar.gz"
      sha256 "d913f054b1fd4cd6a45bcd47c4beefca6b2e0138e7f2cf5a36318a071b330a40"
    end
  end

  def install
    bin.install "uatu"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/uatu --version")
  end
end
